#!/usr/bin/env bash

set -euo pipefail

VPS_CODEX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export VPS_CODEX_DIR

CONFIG_FILE="${VPS_CODEX_CONFIG:-${VPS_CODEX_DIR}/config.env}"
readonly REMOTE_SSH_USER="agent"

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '[vps-codex] %s\n' "$*" >&2
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

load_config() {
  [[ -f "${CONFIG_FILE}" ]] || die "missing ${CONFIG_FILE}; copy config.example.env to config.env and edit it"
  # This is a user-owned shell configuration file and may intentionally use
  # expansions such as $(date ...) for unique resource names.
  # shellcheck disable=SC1090
  source "${CONFIG_FILE}"

  VPS_STATE_FILE="${VPS_STATE_FILE:-${VPS_CODEX_DIR}/.state/current.env}"
  export VPS_STATE_FILE
}

load_state() {
  [[ -f "${VPS_STATE_FILE}" ]] || die "state file not found: ${VPS_STATE_FILE}; run 01-allocate.sh first"
  # State is generated by write_state with shell-escaped values.
  # shellcheck disable=SC1090
  source "${VPS_STATE_FILE}"
  [[ -n "${DROPLET_ID:-}" ]] || die "invalid state file: ${VPS_STATE_FILE}"
}

write_state() {
  local droplet_id="$1"
  local droplet_ip="$2"
  local droplet_name="$3"
  local state_dir
  local temporary_state

  state_dir="$(dirname "${VPS_STATE_FILE}")"
  install -d -m 0700 "${state_dir}" || return 1
  temporary_state="$(mktemp "${VPS_STATE_FILE}.tmp.XXXXXX")" || return 1
  chmod 0600 "${temporary_state}" || {
    rm -f "${temporary_state}"
    return 1
  }
  {
    printf 'DROPLET_ID=%q\n' "${droplet_id}"
    printf 'DROPLET_IP=%q\n' "${droplet_ip}"
    printf 'DROPLET_NAME=%q\n' "${droplet_name}"
    printf 'KNOWN_HOSTS_FILE=%q\n' "${VPS_STATE_FILE}.known_hosts"
    printf 'SSH_CONFIG_FILE=%q\n' "${VPS_STATE_FILE}.ssh_config"
    printf 'SSH_ALIAS=%q\n' "codex-vps-${droplet_id}"
    printf 'CREATED_AT=%q\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >"${temporary_state}" || {
    rm -f "${temporary_state}"
    return 1
  }
  mv "${temporary_state}" "${VPS_STATE_FILE}" || {
    rm -f "${temporary_state}"
    return 1
  }
}

remote_ssh() {
  [[ -n "${DROPLET_IP:-}" ]] || die "Droplet does not have a public IP yet"
  ssh \
    -i "${SSH_PRIVATE_KEY_FILE}" \
    -o "UserKnownHostsFile=${KNOWN_HOSTS_FILE}" \
    -o StrictHostKeyChecking=accept-new \
    -o BatchMode=yes \
    -o ConnectTimeout=10 \
    -o ServerAliveInterval=15 \
    -o ServerAliveCountMax=4 \
    "${REMOTE_SSH_USER}@${DROPLET_IP}" "$@"
}

remote_ssh_tty() {
  [[ -n "${DROPLET_IP:-}" ]] || die "Droplet does not have a public IP yet"
  ssh -tt \
    -i "${SSH_PRIVATE_KEY_FILE}" \
    -o "UserKnownHostsFile=${KNOWN_HOSTS_FILE}" \
    -o StrictHostKeyChecking=accept-new \
    -o BatchMode=yes \
    -o ConnectTimeout=10 \
    -o ServerAliveInterval=15 \
    -o ServerAliveCountMax=4 \
    "${REMOTE_SSH_USER}@${DROPLET_IP}" "$@"
}

remote_exec() {
  local command=""
  local quoted
  local argument

  for argument in "$@"; do
    printf -v quoted '%q' "${argument}"
    command+="${command:+ }${quoted}"
  done
  remote_ssh "${command}"
}
