#!/usr/bin/env bash

set -euo pipefail

VPS_CODEX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export VPS_CODEX_DIR

CONFIG_FILE="${VPS_CODEX_CONFIG:-${VPS_CODEX_DIR}/config.env}"
readonly REMOTE_SSH_USER="agent"

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '[vps-codex] %s\n' "$*" >&2
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

doctl_http_status() {
  sed -nE '
    s/.*: ([0-9]{3}) \(request .*/\1/
    t found
    s/^Error: [A-Z]+ [^[:space:]]+: ([0-9]{3})([[:space:]].*)?$/\1/
    t found
    b
    :found
    p
    q
  '
}

acquire_lifecycle_lock() {
  local lock_dir
  local lock_pid
  local manual_cleanup
  local recovery_dir

  lock_dir="${VPS_STATE_FILE}.lock"
  recovery_dir="${lock_dir}.recovery"
  manual_cleanup="after confirming no create/destroy process is running, clear it with: rm -f '${lock_dir}/pid' && rmdir '${lock_dir}'"
  install -d -m 0700 "$(dirname "${VPS_STATE_FILE}")"

  [[ ! -d "${recovery_dir}" ]] || die "another process is recovering the lifecycle lock at ${lock_dir}; retry shortly"
  if mkdir -m 0700 "${lock_dir}" 2>/dev/null; then
    # A recovery process may have started after the check above. Do not claim
    # the lock while it is serializing stale-owner removal.
    if [[ -d "${recovery_dir}" ]]; then
      rmdir "${lock_dir}" 2>/dev/null || true
      die "another process is recovering the lifecycle lock at ${lock_dir}; retry shortly"
    fi
  else
    if ! mkdir -m 0700 "${recovery_dir}" 2>/dev/null; then
      die "lifecycle lock exists at ${lock_dir}; another create/destroy process may be running; ${manual_cleanup}"
    fi

    lock_pid=""
    if [[ -r "${lock_dir}/pid" ]]; then
      lock_pid="$(cat "${lock_dir}/pid" 2>/dev/null || true)"
    fi
    if [[ -z "${lock_pid}" ]]; then
      rmdir "${recovery_dir}" 2>/dev/null || true
      die "lifecycle lock at ${lock_dir} has no owner PID; refusing to steal a lock whose creator may still be starting; retry first, then ${manual_cleanup}"
    fi
    if [[ "${lock_pid}" =~ ^[1-9][0-9]*$ ]] && kill -0 "${lock_pid}" 2>/dev/null; then
      rmdir "${recovery_dir}" 2>/dev/null || true
      die "lifecycle lock at ${lock_dir} is owned by live process ${lock_pid}"
    fi
    if [[ -n "${lock_pid}" && ! "${lock_pid}" =~ ^[1-9][0-9]*$ ]]; then
      rmdir "${recovery_dir}" 2>/dev/null || true
      die "lifecycle lock at ${lock_dir} has unreadable owner metadata; ${manual_cleanup}"
    fi

    rm -f "${lock_dir}/pid"
    if ! rmdir "${lock_dir}" 2>/dev/null || ! mkdir -m 0700 "${lock_dir}" 2>/dev/null; then
      rmdir "${recovery_dir}" 2>/dev/null || true
      die "could not safely recover stale lifecycle lock at ${lock_dir}"
    fi
    log "recovered stale lifecycle lock${lock_pid:+ from process ${lock_pid}}"
    rmdir "${recovery_dir}" 2>/dev/null || true
  fi
  LIFECYCLE_LOCK_DIR="${lock_dir}"
  printf '%s\n' "$$" >"${LIFECYCLE_LOCK_DIR}/pid" || {
    rmdir "${LIFECYCLE_LOCK_DIR}" 2>/dev/null || true
    die "could not record lifecycle lock ownership"
  }
}

release_lifecycle_lock() {
  local cleanup_dir
  local lock_pid

  [[ -n "${LIFECYCLE_LOCK_DIR:-}" ]] || return 0
  [[ -r "${LIFECYCLE_LOCK_DIR}/pid" ]] || return 0
  lock_pid="$(cat "${LIFECYCLE_LOCK_DIR}/pid")"
  [[ "${lock_pid}" == "$$" ]] || return 0
  cleanup_dir="${LIFECYCLE_LOCK_DIR}.release.$$"
  if mv "${LIFECYCLE_LOCK_DIR}" "${cleanup_dir}" 2>/dev/null; then
    rm -f "${cleanup_dir}/pid"
    rmdir "${cleanup_dir}" 2>/dev/null || true
  fi
}

load_config() {
  [[ -f "${CONFIG_FILE}" ]] || die "missing ${CONFIG_FILE}; copy config.example.env to config.env and edit it"
  # This is a user-owned shell configuration file and may intentionally use
  # expansions such as $(date ...) for unique resource names.
  # shellcheck disable=SC1090
  source "${CONFIG_FILE}"

  VPS_STATE_FILE="${VPS_STATE_FILE:-${VPS_CODEX_DIR}/.state/current.env}"
  export VPS_STATE_FILE
}

load_state() {
  [[ -f "${VPS_STATE_FILE}" ]] || die "state file not found: ${VPS_STATE_FILE}; run create.sh first"
  # State is generated by write_state with shell-escaped values.
  # shellcheck disable=SC1090
  source "${VPS_STATE_FILE}"
  [[ -n "${DROPLET_ID:-}" ]] || die "invalid state file: ${VPS_STATE_FILE}"
}

write_state() {
  local droplet_id="$1"
  local droplet_ip="$2"
  local droplet_name="$3"
  local state_dir
  local temporary_state

  state_dir="$(dirname "${VPS_STATE_FILE}")"
  install -d -m 0700 "${state_dir}" || return 1
  temporary_state="$(mktemp "${VPS_STATE_FILE}.tmp.XXXXXX")" || return 1
  chmod 0600 "${temporary_state}" || {
    rm -f "${temporary_state}"
    return 1
  }
  {
    printf 'DROPLET_ID=%q\n' "${droplet_id}"
    printf 'DROPLET_IP=%q\n' "${droplet_ip}"
    printf 'DROPLET_NAME=%q\n' "${droplet_name}"
    printf 'KNOWN_HOSTS_FILE=%q\n' "${VPS_STATE_FILE}.known_hosts"
    printf 'SSH_CONFIG_FILE=%q\n' "${VPS_STATE_FILE}.ssh_config"
    printf 'SSH_ALIAS=%q\n' "codex-vps-${droplet_id}"
    printf 'CREATED_AT=%q\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >"${temporary_state}" || {
    rm -f "${temporary_state}"
    return 1
  }
  mv "${temporary_state}" "${VPS_STATE_FILE}" || {
    rm -f "${temporary_state}"
    return 1
  }
}

remote_ssh() {
  [[ -n "${DROPLET_IP:-}" ]] || die "Droplet does not have a public IP yet"
  ssh \
    -i "${SSH_PRIVATE_KEY_FILE}" \
    -o "UserKnownHostsFile=${KNOWN_HOSTS_FILE}" \
    -o StrictHostKeyChecking=accept-new \
    -o BatchMode=yes \
    -o ConnectTimeout=10 \
    -o ServerAliveInterval=15 \
    -o ServerAliveCountMax=4 \
    "${REMOTE_SSH_USER}@${DROPLET_IP}" "$@"
}

remote_ssh_tty() {
  [[ -n "${DROPLET_IP:-}" ]] || die "Droplet does not have a public IP yet"
  ssh -tt \
    -i "${SSH_PRIVATE_KEY_FILE}" \
    -o "UserKnownHostsFile=${KNOWN_HOSTS_FILE}" \
    -o StrictHostKeyChecking=accept-new \
    -o BatchMode=yes \
    -o ConnectTimeout=10 \
    -o ServerAliveInterval=15 \
    -o ServerAliveCountMax=4 \
    "${REMOTE_SSH_USER}@${DROPLET_IP}" "$@"
}

remote_exec() {
  local command=""
  local quoted
  local argument

  for argument in "$@"; do
    printf -v quoted '%q' "${argument}"
    command+="${command:+ }${quoted}"
  done
  remote_ssh "${command}"
}
