#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

forget_unresolved_allocation=false
confirm_missing_droplet=false
confirm_missing_snapshot=false
confirm_request_not_accepted=false
forget_unrevoked_token=false
instance_id=""
instance_option_seen=false
while (( $# > 0 )); do
  case "$1" in
    --instance)
      (( $# >= 2 )) || die "--instance requires an instance ID"
      [[ "${instance_option_seen}" != true ]] || die "--instance may only be specified once"
      [[ -n "$2" ]] || die "--instance requires a nonempty instance ID"
      instance_option_seen=true
      instance_id="$2"
      shift 2
      ;;
    --forget-unresolved-allocation)
      forget_unresolved_allocation=true
      shift
      ;;
    --confirm-missing-droplet)
      confirm_missing_droplet=true
      shift
      ;;
    --confirm-missing-snapshot)
      confirm_missing_snapshot=true
      shift
      ;;
    --confirm-request-not-accepted)
      confirm_request_not_accepted=true
      shift
      ;;
    --forget-unrevoked-token)
      forget_unrevoked_token=true
      shift
      ;;
    *)
      die "usage: ./vps_destroy.sh [--instance INSTANCE_ID] [--forget-unresolved-allocation] [--confirm-missing-droplet] [--confirm-missing-snapshot] [--confirm-request-not-accepted] [--forget-unrevoked-token]"
      ;;
  esac
done
[[ "${instance_option_seen}" == true ]] || die "usage: ./vps_destroy.sh --instance INSTANCE_ID [--forget-unresolved-allocation] [--confirm-missing-droplet] [--confirm-missing-snapshot] [--confirm-request-not-accepted] [--forget-unrevoked-token]"

load_config true
select_instance_state "${instance_id}"
instance_arguments=" --instance ${instance_id}"
log "using instance ${instance_id}"
create_source_argument="'<owner/repository,base-branch>'"
if [[ -f "${VPS_STATE_FILE}.setup" ]]; then
  unset SETUP_BASE_BRANCH SETUP_REPOSITORY
  # Generated by vps_create.sh with shell-escaped values.
  # shellcheck disable=SC1090
  source "${VPS_STATE_FILE}.setup"
  if [[ "${SETUP_REPOSITORY:-}" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ &&
    "${SETUP_BASE_BRANCH:-}" =~ ^[A-Za-z0-9._/-]+$ ]]; then
    create_source_argument="${SETUP_REPOSITORY},${SETUP_BASE_BRANCH}"
  fi
fi
create_command="./vps_create.sh${instance_arguments} ${create_source_argument}"
destroy_command="./vps_destroy.sh${instance_arguments}"

acquire_lifecycle_lock
trap release_lifecycle_lock EXIT

token_state_file="${VPS_STATE_FILE}.github-token"
replacement_journal_file="${token_state_file}.replacement"
allocation_state_file="${VPS_STATE_FILE}.allocation"

validate_instance_credential_isolation() {
  local setup_state_file="${VPS_STATE_FILE}.setup"

  [[ -e "${token_state_file}" || -e "${replacement_journal_file}" ]] || return 0
  unset SETUP_INSTANCE_ID SETUP_CREDENTIAL_ISOLATION_VERSION
  if [[ -f "${setup_state_file}" ]]; then
    # Generated by vps_create.sh with shell-escaped values.
    # shellcheck disable=SC1090
    source "${setup_state_file}"
  fi
  if [[ "${SETUP_CREDENTIAL_ISOLATION_VERSION:-}" == 1 && "${SETUP_INSTANCE_ID:-}" == "${instance_id}" ]]; then
    return 0
  fi
  if [[ "${forget_unrevoked_token}" == true ]]; then
    rm -f "${token_state_file}" "${replacement_journal_file}"
    log "WARNING: forgot unversioned credential state without revoking it; it may be shared with another pre-isolation instance"
    return 0
  fi
  die "instance credential ownership is unversioned or belongs to another instance; refusing to revoke it. Audit or manually revoke it, then rerun ${destroy_command} --forget-unrevoked-token"
}

validate_instance_credential_isolation

revoke_github_token_values() {
  local response_file

  if ! command -v curl >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
    log "WARNING: curl and jq are required to revoke the GitHub credential"
    return 1
  fi
  if ! response_file="$(mktemp "$(dirname "${token_state_file}")/github-revoke.XXXXXX")"; then
    log "WARNING: could not create a protected GitHub revocation response file"
    return 1
  fi
  if ! chmod 0600 "${response_file}"; then
    rm -f "${response_file}"
    log "WARNING: could not protect the GitHub revocation response file"
    return 1
  fi

  log "revoking ${#} known VPS-specific GitHub credential(s)"
  if printf '%s\n' "$@" | jq -Rsc 'split("\n") | map(select(length > 0)) | {credentials: .}' | \
    curl --fail-with-body --silent --show-error \
      --request POST \
      --header 'Accept: application/vnd.github+json' \
      --header 'Content-Type: application/json' \
      --header 'X-GitHub-Api-Version: 2022-11-28' \
      --data-binary @- \
      --output "${response_file}" \
      https://api.github.com/credentials/revoke; then
    rm -f "${response_file}"
    log "revoked the known VPS-specific GitHub credential(s)"
    return 0
  fi

  rm -f "${response_file}"
  log "WARNING: GitHub credential revocation failed; the protected token remains at ${token_state_file} for retry and will expire on its configured date"
  return 1
}

revoke_github_credentials() {
  local credential
  local existing
  local github_token
  local -a credentials=()

  if [[ -e "${token_state_file}" ]]; then
    if [[ -s "${token_state_file}" ]]; then
      github_token="$(cat "${token_state_file}")" || {
        log "WARNING: could not read the retained GitHub credential at ${token_state_file}"
        return 1
      }
      credentials+=("${github_token}")
    else
      rm -f "${token_state_file}"
      log "removed an empty GitHub credential marker"
    fi
  fi

  if [[ -e "${replacement_journal_file}" ]]; then
    [[ -s "${replacement_journal_file}" ]] || {
      rm -f "${replacement_journal_file}"
      log "removed an empty GitHub credential replacement journal"
    }
    if [[ -s "${replacement_journal_file}" ]]; then
      unset REPLACEMENT_OLD_GITHUB_TOKEN REPLACEMENT_NEW_GITHUB_TOKEN
      # Generated by vps_create.sh with shell-escaped values.
      # shellcheck disable=SC1090
      source "${replacement_journal_file}"
      if [[ "${REPLACEMENT_OLD_GITHUB_TOKEN:-}" != github_pat_* ||
        "${REPLACEMENT_NEW_GITHUB_TOKEN:-}" != github_pat_* ]]; then
        log "WARNING: invalid credential replacement journal at ${replacement_journal_file}"
        return 1
      fi
      for credential in "${REPLACEMENT_OLD_GITHUB_TOKEN}" "${REPLACEMENT_NEW_GITHUB_TOKEN}"; do
        if (( ${#credentials[@]} > 0 )); then
          for existing in "${credentials[@]}"; do
            [[ "${credential}" != "${existing}" ]] || continue 2
          done
        fi
        credentials+=("${credential}")
      done
      unset REPLACEMENT_OLD_GITHUB_TOKEN REPLACEMENT_NEW_GITHUB_TOKEN
    fi
  fi

  if (( ${#credentials[@]} > 0 )); then
    revoke_github_token_values "${credentials[@]}" || return 1
  fi
  rm -f "${token_state_file}" "${replacement_journal_file}"
}

revoke_or_explicitly_forget_github_token() {
  if revoke_github_credentials; then
    return 0
  fi
  if [[ "${forget_unrevoked_token}" == true ]]; then
    rm -f "${token_state_file}" "${replacement_journal_file}"
    log "WARNING: forgot all known unrevoked GitHub credentials at operator request; revoke them manually or accept their remaining expiration windows"
    return 0
  fi
  return 1
}

if [[ -f "${VPS_STATE_FILE}.paused" || -f "${VPS_STATE_FILE}.transition" ]]; then
  require_command doctl
  require_command jq
  active_droplet_id=""
  source_droplet_id=""
  target_droplet_id=""
  target_lifecycle_tag=""
  owned_snapshot_id=""
  owned_snapshot_name=""
  owned_snapshot_source_id=""
  owned_snapshot_region=""
  owned_snapshot_disk=0

  if [[ -f "${VPS_STATE_FILE}.paused" ]]; then
    load_paused_state
    owned_snapshot_id="${SNAPSHOT_ID}"
    owned_snapshot_name="${SNAPSHOT_NAME}"
    owned_snapshot_source_id="${SNAPSHOT_SOURCE_DROPLET_ID}"
    owned_snapshot_region="${DROPLET_REGION}"
    owned_snapshot_disk="${SOURCE_DISK_SIZE:-0}"
  fi
  if [[ -f "${VPS_STATE_FILE}.transition" ]]; then
    load_transition_state
    owned_snapshot_id="${SNAPSHOT_ID:-${owned_snapshot_id}}"
    owned_snapshot_name="${SNAPSHOT_NAME:-${owned_snapshot_name}}"
    owned_snapshot_source_id="${SOURCE_DROPLET_ID:-${owned_snapshot_source_id}}"
    owned_snapshot_region="${SOURCE_REGION:-${owned_snapshot_region}}"
    owned_snapshot_disk="${SOURCE_DISK_SIZE:-${owned_snapshot_disk}}"
    if [[ "${TRANSITION_KIND}" == pause && "${SOURCE_DELETE_CONFIRMED:-0}" != 1 ]]; then
      source_droplet_id="${SOURCE_DROPLET_ID:-}"
    fi
    if [[ "${TRANSITION_KIND}" == resume ]]; then
      target_droplet_id="${TARGET_DROPLET_ID:-}"
      target_lifecycle_tag="${TARGET_LIFECYCLE_TAG:-}"
    fi
  fi

  if [[ "${TRANSITION_KIND:-}" == pause && "${SNAPSHOT_REQUESTED:-0}" == 1 && -z "${owned_snapshot_id}" ]]; then
    snapshots_json="$(doctl compute snapshot list --resource droplet --output json)" ||
      die "could not reconcile the pending snapshot before teardown"
    snapshot_matches="$(jq --arg name "${SNAPSHOT_NAME}" --arg source "${SOURCE_DROPLET_ID}" --arg region "${SOURCE_REGION}" \
      '[.[] | select(.name == $name and .resource_type == "droplet" and .resource_id == $source and (.regions | index($region) != null))]' <<<"${snapshots_json}")"
    snapshot_match_count="$(jq 'length' <<<"${snapshot_matches}")"
    if [[ "${snapshot_match_count}" == 1 ]]; then
      owned_snapshot_id="$(jq -er '.[0].id' <<<"${snapshot_matches}")"
      SNAPSHOT_ID="${owned_snapshot_id}"
      write_transition_state
    elif [[ "${snapshot_match_count}" != 0 ]]; then
      die "multiple snapshots match the pending request; refusing partial teardown"
    elif [[ "${confirm_request_not_accepted}" == true ]]; then
      SNAPSHOT_REQUESTED=0
      write_transition_state
      log "accepted operator confirmation that the pending snapshot request was not accepted"
    else
      die "snapshot creation may still complete; retry later, or after independently confirming rejection use --confirm-request-not-accepted"
    fi
  fi
  if [[ -f "${VPS_STATE_FILE}" ]]; then
    load_state
    active_droplet_id="${DROPLET_ID}"
  fi

  # Used by write_transition_state through its fixed variable list.
  # shellcheck disable=SC2034
  TEARDOWN_STARTED=1
  TARGET_DELETE_CONFIRMED="${TARGET_DELETE_CONFIRMED:-0}"
  if [[ -f "${VPS_STATE_FILE}.transition" ]]; then
    write_transition_state
  fi

  if [[ "${TARGET_DELETE_CONFIRMED}" != 1 && -z "${target_droplet_id}" && -n "${target_lifecycle_tag}" && "${TARGET_CREATE_REQUESTED:-0}" == 1 ]]; then
    matches="$(doctl compute droplet list --tag-name "${target_lifecycle_tag}" --output json)" ||
      die "could not reconcile replacement Droplet by lifecycle tag"
    match_count="$(jq 'length' <<<"${matches}")"
    if [[ "${match_count}" == 1 ]]; then
      target_droplet_id="$(jq -er '.[0].id' <<<"${matches}")"
      TARGET_DROPLET_ID="${target_droplet_id}"
      write_transition_state
    elif [[ "${match_count}" != 0 ]]; then
      die "multiple Droplets have lifecycle tag ${target_lifecycle_tag}; refusing partial teardown"
    elif [[ "${forget_unresolved_allocation}" != true ]]; then
      die "replacement allocation remains uncertain; retry later, or confirm no tagged Droplet exists with --forget-unresolved-allocation"
    fi
  fi

  delete_transition_droplet() {
    local droplet_id="$1"
    local output status http_status
    [[ -n "${droplet_id}" ]] || return 0
    set +e
    output="$(doctl_mutate compute droplet delete "${droplet_id}" --force 2>&1)"
    status=$?
    set -e
    if (( status == 0 )); then
      log "deleted Droplet ${droplet_id}"
      return 0
    fi
    http_status="$(doctl_http_status <<<"${output}")"
    if [[ "${http_status}" == 404 && "${confirm_missing_droplet}" == true ]]; then
      log "accepted operator confirmation that Droplet ${droplet_id} is absent"
      return 0
    fi
    [[ -z "${output}" ]] || printf '%s\n' "${output}" >&2
    return 1
  }

  droplets_confirmed_absent=true
  deleted_ids=""
  for candidate_id in "${active_droplet_id}" "${source_droplet_id}" "$([[ "${TARGET_DELETE_CONFIRMED}" == 1 ]] || printf '%s' "${target_droplet_id}")"; do
    [[ -n "${candidate_id}" ]] || continue
    case " ${deleted_ids} " in *" ${candidate_id} "*) continue ;; esac
    if delete_transition_droplet "${candidate_id}"; then
      deleted_ids="${deleted_ids}${deleted_ids:+ }${candidate_id}"
      [[ "${candidate_id}" != "${active_droplet_id}" ]] || rm -f "${VPS_STATE_FILE}"
      if [[ -f "${VPS_STATE_FILE}.transition" ]]; then
        if [[ "${candidate_id}" == "${SOURCE_DROPLET_ID:-}" ]]; then
          SOURCE_DELETE_CONFIRMED=1
        fi
        if [[ "${candidate_id}" == "${TARGET_DROPLET_ID:-}" ]]; then
          TARGET_DELETE_CONFIRMED=1
        fi
        write_transition_state
      fi
    else
      droplets_confirmed_absent=false
    fi
  done
  [[ "${droplets_confirmed_absent}" == true ]] || die "not every possible Droplet deletion was confirmed; state and credentials retained"

  revoke_status=0
  revoke_or_explicitly_forget_github_token || revoke_status=$?

  snapshot_delete_status=0
  if [[ -n "${owned_snapshot_id}" ]]; then
    set +e
    snapshot_lookup="$(doctl compute snapshot get "${owned_snapshot_id}" --output json 2>&1)"
    snapshot_lookup_status=$?
    set -e
    if (( snapshot_lookup_status == 0 )); then
      validate_snapshot_json "${snapshot_lookup}" "${owned_snapshot_id}" "${owned_snapshot_name}" \
        "${owned_snapshot_source_id}" "${owned_snapshot_region}" "${owned_snapshot_disk}" ||
        die "owned snapshot ID no longer matches its recorded identity; refusing deletion"
      set +e
      snapshot_output="$(doctl_mutate compute snapshot delete "${owned_snapshot_id}" --force 2>&1)"
      snapshot_delete_status=$?
      set -e
    elif [[ "$(doctl_http_status <<<"${snapshot_lookup}")" == 404 && "${confirm_missing_snapshot}" == true ]]; then
      snapshot_delete_status=0
      log "accepted operator confirmation that snapshot ${owned_snapshot_id} is absent"
    else
      [[ -z "${snapshot_lookup}" ]] || printf '%s\n' "${snapshot_lookup}" >&2
      snapshot_delete_status=1
    fi
    if (( snapshot_delete_status != 0 )); then
      [[ -z "${snapshot_output:-}" ]] || printf '%s\n' "${snapshot_output}" >&2
      log "WARNING: snapshot ${owned_snapshot_id} deletion was not confirmed; credential state was revoked but snapshot ownership state is retained"
    fi
  fi

  if (( snapshot_delete_status == 0 )); then
    rm -f "${VPS_STATE_FILE}.paused"
    rm -f "${VPS_STATE_FILE}.transition"
  fi
  if (( snapshot_delete_status == 0 && revoke_status == 0 )); then
    rm -f "${VPS_STATE_FILE}.known_hosts" "${VPS_STATE_FILE}.ssh_config" \
      "${VPS_STATE_FILE}.setup" "${VPS_STATE_FILE}.remote-control" "${VPS_STATE_FILE}.allocation"
    if [[ -n "${owned_snapshot_id}" && -z "${deleted_ids}" ]]; then
      printf 'Destroyed paused instance %s (snapshot %s). Compute billing had already stopped; snapshot storage has been removed.\n' \
        "${instance_id}" "${owned_snapshot_id}"
    else
      printf 'Destroyed instance %s and removed its owned snapshot storage. DigitalOcean compute billing has stopped.\n' "${instance_id}"
    fi
    exit 0
  fi
  (( snapshot_delete_status == 0 && revoke_status == 0 ))
fi

allocation_cleanup_completed=false
if [[ ! -f "${VPS_STATE_FILE}" && -f "${allocation_state_file}" ]]; then
  # Generated by vps_create.sh with shell-escaped values.
  # shellcheck disable=SC1090
  source "${allocation_state_file}"
  if [[ "${ALLOCATION_REQUESTED:-0}" == 1 ]]; then
    require_command doctl
    require_command jq
    [[ -n "${ALLOCATION_LIFECYCLE_TAG:-}" ]] || die "invalid allocation checkpoint: lifecycle tag is empty; refusing an account-wide lookup"
    allocation_matches="$(doctl compute droplet list --tag-name "${ALLOCATION_LIFECYCLE_TAG}" --output json)"
    allocation_count="$(jq 'length' <<<"${allocation_matches}")"
    if [[ "${allocation_count}" == 1 ]]; then
      allocation_id="$(jq -er '.[0].id' <<<"${allocation_matches}")"
      allocation_name="$(jq -er '.[0].name' <<<"${allocation_matches}")"
      allocation_ip="$(jq -r '.[0].networks.v4[]? | select(.type == "public") | .ip_address' <<<"${allocation_matches}" | head -n 1)"
      if ! write_state "${allocation_id}" "${allocation_ip}" "${allocation_name}"; then
        log "local state is unwritable; deleting reconciled Droplet ${allocation_id} directly"
        set +e
        direct_delete_output="$(doctl compute droplet delete "${allocation_id}" --force 2>&1)"
        direct_delete_status=$?
        set -e
        if (( direct_delete_status != 0 )); then
          [[ -z "${direct_delete_output}" ]] || printf '%s\n' "${direct_delete_output}" >&2
          die "could not save state or delete reconciled Droplet ${allocation_id}; delete that ID manually"
        fi
        rm -f "${allocation_state_file}"
        printf 'Destroyed reconciled Droplet %s despite the unwritable main state file.\n' "${allocation_id}"
        allocation_cleanup_completed=true
      fi
    elif [[ "${allocation_count}" == 0 ]]; then
      if [[ "${forget_unresolved_allocation}" == true ]]; then
        rm -f "${allocation_state_file}"
        printf 'Forgot the unresolved allocation checkpoint after finding no tagged Droplet.\n'
        allocation_cleanup_completed=true
      else
        die "the allocation request has no visible Droplet yet; checkpoint retained. Retry later, or after independently confirming no Droplet exists run: ${destroy_command} --forget-unresolved-allocation"
      fi
    else
      die "multiple Droplets have lifecycle tag ${ALLOCATION_LIFECYCLE_TAG}; delete the extras manually"
    fi
  else
    rm -f "${allocation_state_file}"
    printf 'Cleaned up the allocation checkpoint; no request had been sent.\n'
    allocation_cleanup_completed=true
  fi
  rm -f "${allocation_state_file}"
fi

if [[ ! -f "${VPS_STATE_FILE}" ]]; then
  if [[ -e "${token_state_file}" || -e "${replacement_journal_file}" ]]; then
    revoke_or_explicitly_forget_github_token || die "credential revocation failed; rerun ${destroy_command} to retry, or after manual revocation run ${destroy_command} --forget-unrevoked-token"
    rm -f "${VPS_STATE_FILE}.setup" "${VPS_STATE_FILE}.remote-control"
    printf 'Cleaned up the retained GitHub credential state; no Droplet state existed.\n'
    exit 0
  elif [[ -e "${VPS_STATE_FILE}.setup" || -e "${VPS_STATE_FILE}.remote-control" ]]; then
    rm -f "${VPS_STATE_FILE}.setup" "${VPS_STATE_FILE}.remote-control"
    printf 'Cleaned up local setup state; no Droplet state existed.\n'
    exit 0
  elif [[ "${allocation_cleanup_completed}" == true ]]; then
    exit 0
  fi
  die "state file not found: ${VPS_STATE_FILE}; create or resume it with ${create_command}"
fi

load_state

if [[ -n "${DROPLET_IP:-}" && -n "${SSH_PRIVATE_KEY_FILE:-}" && -f "${SSH_PRIVATE_KEY_FILE}" ]]; then
  if ( remote_ssh '/usr/local/bin/codex remote-control --json stop >/dev/null 2>&1' ); then
    log "stopped Codex remote control"
  else
    log "remote control was not reachable; continuing with Droplet deletion"
  fi
elif [[ -n "${DROPLET_IP:-}" ]]; then
  log "SSH key is unavailable; skipping optional remote-control stop"
fi

log "destroying Droplet ${DROPLET_ID} (${DROPLET_NAME:-unknown}, ${DROPLET_IP:-IP pending})"
delete_status=0
if ! command -v doctl >/dev/null 2>&1; then
  log "WARNING: required command not found: doctl"
  delete_status=1
else
  set +e
  delete_output="$(doctl compute droplet delete "${DROPLET_ID}" --force 2>&1)"
  delete_status=$?
  set -e
  if (( delete_status != 0 )); then
    http_status="$(doctl_http_status <<<"${delete_output}")"
    if [[ "${http_status}" == 404 ]]; then
      if [[ "${confirm_missing_droplet}" == true ]]; then
        log "accepting operator confirmation that missing Droplet ${DROPLET_ID} is already deleted"
        delete_status=0
      else
        [[ -z "${delete_output}" ]] || printf '%s\n' "${delete_output}" >&2
        log "WARNING: DigitalOcean returned 404, which may indicate a different doctl account; state retained. Verify the account and absence, then run: ${destroy_command} --confirm-missing-droplet"
      fi
    else
      [[ -z "${delete_output}" ]] || printf '%s\n' "${delete_output}" >&2
      log "WARNING: DigitalOcean did not confirm deletion of Droplet ${DROPLET_ID}"
    fi
  fi
fi

revoke_status=0
if (( delete_status == 0 )); then
  revoke_or_explicitly_forget_github_token || revoke_status=$?
else
  log "Droplet deletion was not confirmed; retaining its GitHub credential"
fi

if (( delete_status == 0 )); then
  rm -f \
    "${KNOWN_HOSTS_FILE:-${VPS_STATE_FILE}.known_hosts}" \
    "${SSH_CONFIG_FILE:-${VPS_STATE_FILE}.ssh_config}" \
    "${VPS_STATE_FILE}" \
    "${VPS_STATE_FILE}.allocation" \
    "${VPS_STATE_FILE}.setup" \
    "${VPS_STATE_FILE}.remote-control"
  printf 'Destroyed instance %s (Droplet %s). DigitalOcean compute billing for it has stopped.\n' "${VPS_INSTANCE_ID}" "${DROPLET_ID}"
else
  printf 'WARNING: Droplet %s may still be running and billable; rerun %s.\n' "${DROPLET_ID}" "${destroy_command}" >&2
fi
if (( revoke_status != 0 )); then
  printf 'WARNING: GitHub credential revocation must be retried with %s, or explicitly cleared after manual revocation with %s --forget-unrevoked-token.\n' "${destroy_command}" "${destroy_command}" >&2
fi
(( delete_status == 0 && revoke_status == 0 ))
