#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

(( $# == 0 )) || die "usage: ./vps_list.sh"
load_config true

root="$(instance_state_root)"
printf 'INSTANCE\tSTATUS\tDROPLET_ID\tIP\tSNAPSHOT_ID\tSOURCE\tBRANCH\n'

print_instance() {
  local instance_id="$1"
  local state_file="$2"
  local setup_file="${state_file}.setup"

  local status=""
  local snapshot_id="-"
  unset DROPLET_ID DROPLET_IP SETUP_BASE_BRANCH SETUP_REPOSITORY SETUP_WORK_BRANCH
  unset TRANSITION_VERSION TRANSITION_KIND TRANSITION_PHASE SNAPSHOT_ID SOURCE_DROPLET_ID TARGET_DROPLET_ID TARGET_DROPLET_IP
  unset PAUSED_STATE_VERSION
  if [[ -f "${setup_file}" ]]; then
    # Generated by vps_create.sh with shell-escaped values.
    # shellcheck disable=SC1090
    source "${setup_file}"
  fi
  if [[ -f "${state_file}.transition" ]]; then
    # Generated by write_transition_state with shell-escaped values.
    # shellcheck disable=SC1090
    source "${state_file}.transition"
    case "${TRANSITION_KIND:-}:${TRANSITION_PHASE:-}" in
      pause:pausing-quiescing|pause:pausing-shutdown|pause:pausing-snapshot|pause:pausing-delete-pending|\
      resume:resuming-allocation|resume:resuming-recovery|resume:active-snapshot-cleanup-pending)
        status="${TRANSITION_PHASE}"
        snapshot_id="${SNAPSHOT_ID:-pending}"
        DROPLET_ID="${TARGET_DROPLET_ID:-${SOURCE_DROPLET_ID:--}}"
        DROPLET_IP="${TARGET_DROPLET_IP:--}"
        ;;
      *) status="invalid-transition-state" ;;
    esac
  elif [[ -f "${state_file}.paused" && -f "${state_file}" ]]; then
    status=invalid-terminal-state
    DROPLET_ID=-
    DROPLET_IP=-
  elif [[ -f "${state_file}.paused" ]]; then
    # Generated by write_paused_state with shell-escaped values.
    # shellcheck disable=SC1090
    source "${state_file}.paused"
    if [[ "${PAUSED_STATE_VERSION:-}" == 1 && "${SNAPSHOT_ID:-}" =~ ^[1-9][0-9]*$ ]]; then
      status=paused
      snapshot_id="${SNAPSHOT_ID}"
      DROPLET_ID=-
      DROPLET_IP=-
    else
      status=invalid-paused-state
    fi
  elif [[ -f "${state_file}" ]]; then
    # Generated by write_state with shell-escaped values.
    # shellcheck disable=SC1090
    source "${state_file}"
    if [[ -n "${SETUP_REPOSITORY:-}" && -n "${SETUP_BASE_BRANCH:-}" ]]; then
      source_description="${SETUP_REPOSITORY}@${SETUP_BASE_BRANCH}"
    else
      source_description="pending"
    fi
    if [[ "${DROPLET_ID:-}" =~ ^[1-9][0-9]*$ ]]; then
      status=active
    else
      status=invalid-active-state
    fi
  elif [[ -f "${state_file}.allocation" ]]; then
    if [[ -n "${SETUP_REPOSITORY:-}" && -n "${SETUP_BASE_BRANCH:-}" ]]; then
      source_description="${SETUP_REPOSITORY}@${SETUP_BASE_BRANCH}"
    else
      source_description="unknown"
    fi
    status=allocation-pending
    DROPLET_ID=-
    DROPLET_IP=-
  elif [[ -f "${setup_file}" && -n "${SETUP_REPOSITORY:-}" && -n "${SETUP_BASE_BRANCH:-}" ]]; then
    status=source-reserved
    DROPLET_ID=-
    DROPLET_IP=-
  else
    status=orphaned-local-state
    DROPLET_ID=-
    DROPLET_IP=-
  fi
  if [[ -n "${SETUP_REPOSITORY:-}" && -n "${SETUP_BASE_BRANCH:-}" ]]; then
    source_description="${SETUP_REPOSITORY}@${SETUP_BASE_BRANCH}"
  else
    source_description="unknown"
  fi
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "${instance_id}" "${status}" "${DROPLET_ID:--}" "${DROPLET_IP:--}" "${snapshot_id}" \
    "${source_description}" "${SETUP_WORK_BRANCH:-unknown}"
}

shopt -s nullglob
for instance_dir in "${root}"/*; do
  [[ -d "${instance_dir}" ]] || continue
  [[ -e "${instance_dir}/current.env" || -e "${instance_dir}/current.env.allocation" ||
    -e "${instance_dir}/current.env.paused" || -e "${instance_dir}/current.env.transition" ||
    -e "${instance_dir}/current.env.setup" || -e "${instance_dir}/current.env.github-token" ||
    -e "${instance_dir}/current.env.remote-control" ]] || continue
  print_instance "$(basename "${instance_dir}")" "${instance_dir}/current.env"
done
