#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

(( $# == 0 )) || die "usage: ./vps_list.sh"
load_config true

root="$(instance_state_root)"
printf 'INSTANCE\tSTATUS\tDROPLET_ID\tIP\tSOURCE\tBRANCH\n'

print_instance() {
  local instance_id="$1"
  local state_file="$2"
  local setup_file="${state_file}.setup"

  unset DROPLET_ID DROPLET_IP SETUP_BASE_BRANCH SETUP_REPOSITORY SETUP_WORK_BRANCH
  if [[ -f "${setup_file}" ]]; then
    # Generated by vps_create.sh with shell-escaped values.
    # shellcheck disable=SC1090
    source "${setup_file}"
  fi
  if [[ -f "${state_file}" ]]; then
    # Generated by write_state with shell-escaped values.
    # shellcheck disable=SC1090
    source "${state_file}"
    if [[ -n "${SETUP_REPOSITORY:-}" && -n "${SETUP_BASE_BRANCH:-}" ]]; then
      source_description="${SETUP_REPOSITORY}@${SETUP_BASE_BRANCH}"
    else
      source_description="pending"
    fi
    printf '%s\tactive\t%s\t%s\t%s\t%s\n' \
      "${instance_id}" "${DROPLET_ID:-unknown}" "${DROPLET_IP:-pending}" \
      "${source_description}" "${SETUP_WORK_BRANCH:-pending}"
  elif [[ -f "${state_file}.allocation" ]]; then
    if [[ -n "${SETUP_REPOSITORY:-}" && -n "${SETUP_BASE_BRANCH:-}" ]]; then
      source_description="${SETUP_REPOSITORY}@${SETUP_BASE_BRANCH}"
    else
      source_description="unknown"
    fi
    printf '%s\tallocation-pending\t-\t-\t%s\t%s\n' \
      "${instance_id}" "${source_description}" "${SETUP_WORK_BRANCH:-unknown}"
  elif [[ -f "${setup_file}" && -n "${SETUP_REPOSITORY:-}" && -n "${SETUP_BASE_BRANCH:-}" ]]; then
    printf '%s\tsource-reserved\t-\t-\t%s@%s\t%s\n' \
      "${instance_id}" "${SETUP_REPOSITORY}" "${SETUP_BASE_BRANCH}" "${SETUP_WORK_BRANCH:-unknown}"
  else
    printf '%s\torphaned-local-state\t-\t-\t-\t-\n' "${instance_id}"
  fi
}

shopt -s nullglob
for instance_dir in "${root}"/*; do
  [[ -d "${instance_dir}" ]] || continue
  [[ -e "${instance_dir}/current.env" || -e "${instance_dir}/current.env.allocation" ||
    -e "${instance_dir}/current.env.setup" || -e "${instance_dir}/current.env.github-token" ||
    -e "${instance_dir}/current.env.remote-control" ]] || continue
  print_instance "$(basename "${instance_dir}")" "${instance_dir}/current.env"
done
